---
config:
  theme: redux
  look: classic
  layout: elk
---
flowchart TD

 rawreads>"Raw reads<br>(Nanopore | Pacbio)"] --> initqc


 subgraph Preprocess
     direction LR
     initqc["Initial: read quality check<br>(NanoPlot)"]
     trimming["Quality/adapter trimming<br>(chopper | fitlong)"]  
     dehost["Remove host contamination<br>(hostile)"]
     finalqc["final QC<br>(NanoPlot)"]
     
     reads>"cleaned reads"]
     initqc --> trimming --> dehost --> finalqc --> reads
 end

 
 assembly(["Assembly"])
 denovo["De novo<br>(MetaFlye)"]
 refguided["Reference-guided<br>(MetaCompass)"]
 binning["Binning<br>(VAMB | Semibin2 | metabat2)"]
 annotation["Genome annotation<br>(Bakta)"]

 genesnp["Structural variation<br> Gene duplication/loss<br>(rhea)"]

  %% for future implementation 
  %% othergenomic(["multi-genomic analyses"])
  %% pangenomics["Pangenomics<br>(tmhg-finder)"]
  %% metabolic["Metabolic reconstruction<br>(bakdrive + micom | apollo)"]
  %% othergenomic --> pangenomics & genesnp & metabolic
  
 assembly --> denovo & refguided
 denovo & refguided --> contigs>"contigs"]
 denovo --> binning
 binning & refguided --> annotation
 annotation --> genome>"(meta)genomes,<br>circos plots"]

 pathogen["Pathogen identification<br>(SeqScreen)"]

 subgraph Laptop_Mode["Laptop mode<br>(read based)"]
  taxonomic["Taxonomic profiling<br>(Lemur + MAGnet ; Emu (16S) | Centrifuge | Sylph)"]
 end

 reads --"taxonomic profiling"--> taxonomic  
 reads --"functional annotation"--> pathogen
 reads --"assembly"--> assembly
 reads --"longitudinal analysis"--> genesnp

 %%  Co-analysis for higher confidence
%%  hard to show this even as a sub-graph (distorts the flowchart)
%%  co-analysis["Co-analysis for higher confidence"] 
%%  reads & contigs --> co-analysis --> taxonomic & pathogen 


%% Style rendering
    style contigs fill:#C8E6C9
    style reads fill:#C8E6C9
    style genome fill:#BBDEFB 
    style rawreads fill:#FFE0B2

%% Notes: from v1-whiteboard
%% What could be "Synthetic data" near data types?
%% Preprocessing: 
%%   add length to trimming node (length filtering)
%%   add depth sampling node
%% Functional annotation:
%%   SeqScreen et. al. don't work on laptop. Move to workstation mode?
%%   Rethink functional annotation name to "ARG" and add `AMR++ with the megares 3 db` to it?
%% Metabolic reconstruction:
%%   Bakdrive can take in emu output (Austin). Check and include in the flowchart. 
%% Database: 
%%   Add node to show databases in a node?
%%   Bacteria: GTDB, RefSeq, Plasmid/ARG, viral: ..
%% Final report: Find a way to show the final report in the flowchart?
