---
config:
  theme: redux
  look: classic
  layout: elk
---
flowchart TD

 rawreads["Raw reads<br>(Nanopore | Pacbio)"] --> initqc


 subgraph Preprocess
     direction LR
     initqc["Initial: read quality check<br>(NanoPlot)"]
     trimming["Quality/adapter trimming<br>(chopper | fitlong)"]  
     dehost["Remove host contamination<br>(hostile)"]
     finalqc["final QC<br>(NanoPlot)"]
     initqc --> trimming --> dehost --> finalqc
 end

 subgraph Workstation_Mode["Workstation/Server mode<br>(assembly-based)"]
     assembly(["Assembly"])
     denovo["De novo<br>(Flye | Canu | AutoCycler)"] --> binning
     refguided["Reference-guided<br>(MetaCompass)"]
     binning["Binning<br>(VAMB | Semibin2 | metabat2)"]
     annotation["Genome annotation<br>(Bakta | Prokka)"]
     
     othergenomic(["multi-genomic analyses"])
     pangenomics["Pangenomics<br>(tmhg-finder)"]
     genesnp["Structural variation<br> Gene duplication/loss<br>(rhea)"]
     metabolic["Metabolic reconstruction<br>(bakdrive + micom | apollo)"]
     
     assembly --> denovo & refguided
     binning & refguided --> annotation
     annotation --> othergenomic
     othergenomic --> pangenomics & genesnp & metabolic

    subgraph Laptop_Mode["Laptop mode<br>(read based)"]
     tax16s["Taxonomic profiling<br>(Emu)"]
          
     readanalysis(["Other read based analysis"])
     classification["Read classification<br>(SeqScreen | Centrifuge)"]
     pathogen["Pathogen identification<br>(MAGnet | SeqScreen)"]
     functional["Functional annotation<br>(SeqScreen | EggNOG-mapper | HUMAnN)"]
     
     taxonomic["Taxonomic profiling<br>(Lemur + MAGnet | Centrifuge | Sylph)"]

     readanalysis --> classification & pathogen & functional
    end

 end

 finalqc --"16S amplicon"--> tax16s
 finalqc --"metagenomic"--> taxonomic & readanalysis
 finalqc --"metagenomic"--> assembly
 

%% Notes:
%% What could be "Synthetic data" near data types?
%% Preprocessing: 
%%   add length to trimming node (length filtering)
%%   add depth sampling node
%% Functional annotation:
%%   SeqScreen et. al. don't work on laptop. Move to workstation mode?
%%   Rethink functional annotation name to "ARG" and add `AMR++ with the megares 3 db` to it?
%% Metabolic reconstruction:
%%   Bakdrive can take in emu output (Austin). Check and include in the flowchart. 
%% Database: 
%%   Add node to show databases in a node?
%%   Bacteria: GTDB, RefSeq, Plasmid/ARG, viral: ..
%% Final report: Find a way to show the final report in the flowchart?
