flowchart TD
 subgraph laptop["Laptop mode"]
      direction LR
        asm["Assembly<br>(meta)"]
        metacomp["MetaCompass"]
        flye["Flye"]
        autocycler["AutoCycler"]
        asm --> flye & autocycler
 end
 subgraph cluster["Cluster mode (MetaCompass, Flye, AutoCycler)"]
        Xyz --> asm
 end