%%metro title: Simple Pipeline
%%metro style: light
%%metro line: main | Main | #4CAF50
%%metro line: qc | Quality Control | #2196F3

graph LR
    input[Input]
    initqc>"Initial: read quality check (NanoPlot)"] 
    %% testing bold

    fastqc[FastQC]
    trim[Trimming]
    align[Alignment]
    quant[Quantification]
    multiqc[MultiQC]

    input -->|main| initqc
    input -->|main,qc| Preprocess
    Preprocess -->|main| trim
    trim -->|main| align
    align -->|main| quant
    Preprocess -->|qc| fastqc
    trim -->|qc| fastqc
    quant -->|qc| multiqc
    fastqc -->|qc| multiqc
